name: Build Seal APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Flet and Dependencies
        run: |
          pip install flet yt-dlp mutagen

      - name: Build Android APK
        run: |
          yes | flet build apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Seal-Official-APK
          path: build/apk/*.apk
          
